name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno: [stable, canary]
        os: [macOS-latest, ubuntu-latest, windows-2019]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Install Deno (Unix)
        if: |
          !startsWith(matrix.os, 'windows')
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Install Deno (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $env:GITHUB_PATH

      - name: Upgrade to Deno canary
        if: matrix.deno == 'canary'
        run: deno upgrade --canary

      - name: Test
        run: deno test --unstable --allow-all

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: false
          persist-credentials: false

      - name: Install Deno
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Upgrade to Deno canary
        run: deno upgrade --canary

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint --unstable
